name: xgprl
channels:
 - defaults
 - conda-forge
dependencies:
 - python==3.9
 - cycler==0.10.0
 - pandas==1.3.3
 - matplotlib==3.4.3
 - numpy==1.21.2
 - pygraphviz==1.7
 - pyparsing==2.4.7
 - python-dateutil==2.8.2
 - pyyaml==5.4.1 
 - scikit-learn==0.24.2
 - scipy==1.7.1
 - six==1.16.0 
 - threadpoolctl==2.2.0
 - typing-extensions==3.10.0.2
 - pip
 - pip:
   - deap==1.3.1
   - joblib==1.0.1
   - kiwisolver==1.3.2
   - pillow==8.3.2
   - psutil==5.8.0
   - pytz==2021.1
   - sklearn==0.0
   - qdpy==0.1.2.1
   - gym==0.20.0
   - git+https://github.com/benelot/pybullet-gym