algorithm:
  name: algo.nqdLambda
  args:
    save_every: None
    batch_size: 500
    lambda_: 1000
    ngen: 2000
    cxpb: 0.05
    mutpb: 0.9
    show_warnings: False
    verbose: False


population:
  init_size: 1000
  args:
    max_items_per_bin: 5
    shape: [20,10,8]
    features_domain: [[0,100],[0,20],[0, 8]]
    fitness_domain: [[-500_000.0, 500.0]]

selection:
  name: selNSGA2
  args:

individual: Tree

params:
  env: "LunarLanderContinuous-v2"
  function_set: extended
  c: 0.0
  n_episodes: 3
  n_steps: 2000
  gamma: 1
  tree_max_depth: 10
  n_thread: 16