algorithm:
  name: algo.qdLambda
  args:
    save_every: 10
    batch_size: 100
    lambda_: 500
    ngen: 2000
    cxpb: 0.0
    mutpb: 1.0
    show_warnings: True
    verbose: True


population:
  init_size: 1000
  args:
    shape: [10, 10]
    max_items_per_bin: 10
    features_domain: [[0, 20], [-1000,0]]
    fitness_domain: [[-200_000.0, 2600.0],]

selection:
  name: selQDRandom
  args:

individual: sTree

params:
  env: BipedalWalker-v3
  function_set: extended
  c: 0.0
  n_episodes: 3
  n_steps: 1000
  gamma: 1.0
  features_kept: [True,True]
  tree_max_depth: 10
  n_thread: 16
